sonar.organization=YOUR_SONARCLOUD_ORG_KEY
sonar.projectKey=YOUR_SONARCLOUD_PROJECT_KEY
sonar.projectName=14 Improving Quality - Todo Frontend

sonar.sources=react-frontend/src
sonar.tests=react-frontend/src
sonar.test.inclusions=**/*.test.js
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**

sonar.javascript.lcov.reportPaths=react-frontend/coverage/lcov.info
